### ISSUE TITLE
BUG IN 320Kbps

### ISSUE THREAD

**Issue by Birdman704** [Sorrow446/Napster-Downloader#3] opened 2022-08-09 07:32 UTC
When downloading in 320 (option 4) it seems that the download does not work well. The downloads are damaged.

In FLAC it works fine
Thank you very much

**Comment by Sorrow446** [comment] 2022-08-10 10:51
Dupe of https://github.com/Sorrow446/Napster-Downloader/issues/2.

**Closed** 2024-02-08 15:21 UTC
